# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: High Branch Brewing Co
address: 325 McGill Ave Suite 148
city: Concord
state: NC
zip: 28027
phone: (704) 706-3807
email: info@highbranchbrewing.com
description: High Branch Brewing is a family-run artisanal brewery located in the historic Gibson Mill in Concord, North Carolina. We focus on Belgian inspired and hop forward ales, with an emphasis on fermentation profiles.
keywords: High Branch Brewing, Concord Brewery, Artisanal Brewery
baseurl: ""
url: ""
facebook_username: HighBranchBrewing
twitter_username: highbranchbeer
instagram_username: highbranchbeer
tj_email: tj@highbranchbrewing.com
maureen_email: maureen@highbranchbrewing.com
collections:
  beer:
    output: true
    permalink: /beer/:path/
  events:
    output: true
    permalink: /events/:path/
markdown: kramdown
future: true